In [1]:
# import the necessary libraries in Python: 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [4]:
# Load the dataset (replace with your dataset path)
df = pd.read_excel("heart_disease.xlsx")

# Display the first few rows of the dataset
df.head()

age                                       Age in years
0    Gender                       Gender ; Male - 1, Female -0
1        cp                                    Chest pain type
2  trestbps                             Resting blood pressure
3      chol                                cholesterol measure
4       fbs  (fasting blood sugar > 120 mg/dl) (1 = true; 0...

In [3]:
pip install openpyxl


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd

# Load the dataset (adjust the file path to your actual file location)
df = pd.read_excel('heart_disease.xlsx')  # Make sure to use read_excel instead of read_csv

# Check for missing values
missing_values = df.isnull().sum()
print(missing_values)


age             0
Age in years    0
dtype: int64


In [5]:
# Check for duplicate rows
print(df.duplicated().sum())  # This will print the number of duplicate rows

# Remove duplicates (if any)
df = df.drop_duplicates()


0


In [6]:
# Check the data types of all columns
print(df.dtypes)


age             object
Age in years    object
dtype: object


In [7]:
# Check if there are any non-numeric values in the 'age' and 'Age in years' columns
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df['Age in years'] = pd.to_numeric(df['Age in years'], errors='coerce')

# Check for any NaN values that might have been created
print(df[['age', 'Age in years']].isnull().sum())


age             12
Age in years    12
dtype: int64


In [9]:
# Impute missing values with the median, without using inplace=True
df['age'] = df['age'].fillna(df['age'].median())
df['Age in years'] = df['Age in years'].fillna(df['Age in years'].median())

# Verify again that the missing values have been handled
print(df[['age', 'Age in years']].isnull().sum())


age             12
Age in years    12
dtype: int64


In [10]:
# Display rows where 'age' or 'Age in years' have NaN values
print(df[df['age'].isnull()])
print(df[df['Age in years'].isnull()])


    age  Age in years
0   NaN           NaN
1   NaN           NaN
2   NaN           NaN
3   NaN           NaN
4   NaN           NaN
5   NaN           NaN
6   NaN           NaN
7   NaN           NaN
8   NaN           NaN
9   NaN           NaN
10  NaN           NaN
11  NaN           NaN
    age  Age in years
0   NaN           NaN
1   NaN           NaN
2   NaN           NaN
3   NaN           NaN
4   NaN           NaN
5   NaN           NaN
6   NaN           NaN
7   NaN           NaN
8   NaN           NaN
9   NaN           NaN
10  NaN           NaN
11  NaN           NaN


In [11]:
# Print the first few rows of the dataset to check the raw data
print(df.head(20))


    age  Age in years
0   NaN           NaN
1   NaN           NaN
2   NaN           NaN
3   NaN           NaN
4   NaN           NaN
5   NaN           NaN
6   NaN           NaN
7   NaN           NaN
8   NaN           NaN
9   NaN           NaN
10  NaN           NaN
11  NaN           NaN


In [12]:
# Drop the 'age' and 'Age in years' columns if they are not useful
df = df.drop(columns=['age', 'Age in years'])

# Verify the data after dropping the columns
print(df.head(20))


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [14]:
# Check for any missing values in the updated dataset
print(df.isnull().sum())


Series([], dtype: float64)


In [16]:
# Check for categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_columns)


Categorical columns: Index([], dtype='object')


In [17]:
# Check data types of all columns
print(df.dtypes)


Series([], dtype: object)


In [19]:
print(df.head())  # Show the first 5 rows of the dataset


Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]


In [20]:
# Ensure you are loading the dataset correctly
df = pd.read_excel('heart_disease.xlsx')  # Use the correct path to your file
print(df.head())  # Check the first few rows to confirm data is loaded


        age                                       Age in years
0    Gender                       Gender ; Male - 1, Female -0
1        cp                                    Chest pain type
2  trestbps                             Resting blood pressure
3      chol                                cholesterol measure
4       fbs  (fasting blood sugar > 120 mg/dl) (1 = true; 0...


In [23]:
# Check the shape of the DataFrame (number of rows and columns)
print(df.shape)


(11, 2)


In [25]:
# Load the Excel file
xls = pd.ExcelFile('heart_disease.xlsx')

# List all sheet names to find the correct one
print(xls.sheet_names)


['Description', 'Heart_disease']


In [26]:
# Load the 'Heart_disease' sheet
df = pd.read_excel('heart_disease.xlsx', sheet_name='Heart_disease')

# Check the first few rows to inspect the data
print(df.head())


   age   sex               cp  trestbps  chol    fbs         restecg  thalch  \
0   63  Male   typical angina       145   233   True  lv hypertrophy     150   
1   41  Male  atypical angina       135   203  False          normal     132   
2   57  Male     asymptomatic       140   192  False          normal     148   
3   52  Male   typical angina       118   186  False  lv hypertrophy     190   
4   57  Male     asymptomatic       110   201  False          normal     126   

   exang  oldpeak        slope          thal  num  
0  False      2.3  downsloping  fixed defect    0  
1  False      0.0         flat  fixed defect    0  
2  False      0.4         flat  fixed defect    0  
3  False      0.0         flat  fixed defect    0  
4   True      1.5         flat  fixed defect    0  


In [27]:
# Check for missing values
print(df.isnull().sum())

# Handle missing values (you can fill or drop depending on the situation)
df = df.dropna()  # or you can fillna(df['column'].mode()[0]) for specific columns


age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalch       0
exang        0
oldpeak     62
slope        0
thal         0
num          0
dtype: int64


In [30]:
# Fill missing values in other columns (if applicable)
df['oldpeak'] = df['oldpeak'].fillna(df['oldpeak'].median())
# Repeat for other columns that have missing values


In [34]:
# Replace 'FALSE' with 0 and 'TRUE' with 1 in the 'exang' column
df['exang'] = df['exang'].replace({'FALSE': 0, 'TRUE': 1})

# Now apply LabelEncoder for the other categorical columns if needed
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Encode binary categorical features
df['sex'] = label_encoder.fit_transform(df['sex'])
df['fbs'] = label_encoder.fit_transform(df['fbs'])
df['exang'] = label_encoder.fit_transform(df['exang'])

# For multi-class categorical features, use One-Hot Encoding
df = pd.get_dummies(df, columns=['cp', 'restecg', 'slope', 'thal'], drop_first=True)

# Verify the data after encoding
print(df.head())


   age  sex  trestbps  chol  fbs  thalch  exang  oldpeak  num  \
0   63    1       145   233    1     150      0      2.3    0   
1   41    1       135   203    0     132      0      0.0    0   
2   57    1       140   192    0     148      0      0.4    0   
3   52    1       118   186    0     190      0      0.0    0   
4   57    1       110   201    0     126      1      1.5    0   

   cp_atypical angina  cp_non-anginal  cp_typical angina  restecg_normal  \
0               False           False               True           False   
1                True           False              False            True   
2               False           False              False            True   
3               False           False               True           False   
4               False           False              False            True   

   restecg_st-t abnormality  slope_flat  slope_upsloping  thal_normal  \
0                     False       False            False        False   
1     

In [35]:
# Define the target and features
X = df.drop(columns=['num'])  # Features (all columns except the target)
y = df['num']  # Target column


In [36]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Check the shape of the resulting datasets
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)


(676, 17) (170, 17) (676,) (170,)


In [40]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Scale the training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale the test data using the same scaler
X_test_scaled = scaler.transform(X_test)


In [41]:
from sklearn.linear_model import LogisticRegression

# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=2000)  # Increase max_iter if needed
model.fit(X_train_scaled, y_train)


LogisticRegression(max_iter=2000)

In [42]:
y_pred = model.predict(X_test_scaled)


In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)


Accuracy: 0.5941176470588235
Confusion Matrix:
[[68  9  2  1  0]
 [13 25  2  1  0]
 [ 1  8  4  1  0]
 [ 5 14  4  4  0]
 [ 0  4  1  3  0]]


In [44]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Step 1: Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Fit and transform the training data
X_test_scaled = scaler.transform(X_test)  # Transform the test data

# Step 2: Train the Logistic Regression model
model = LogisticRegression(max_iter=2000)
model.fit(X_train_scaled, y_train)

# Step 3: Make predictions
y_pred = model.predict(X_test_scaled)

# Step 4: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)


Accuracy: 0.5941176470588235
Confusion Matrix:
[[68  9  2  1  0]
 [13 25  2  1  0]
 [ 1  8  4  1  0]
 [ 5 14  4  4  0]
 [ 0  4  1  3  0]]


In [46]:
# Import necessary libraries
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# Set up hyperparameter grid for the Decision Tree
param_grid = {
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
}

# Initialize GridSearchCV with the DecisionTreeClassifier and the parameter grid
grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid, cv=5)

# Fit the GridSearchCV to the training data
grid_search.fit(X_train, y_train)

# Print best parameters from Grid Search
print("Best Parameters:", grid_search.best_params_)
print("Best Cross-validation Score:", grid_search.best_score_)

# Use the best model
best_model = grid_search.best_estimator_


Best Parameters: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Cross-validation Score: 0.5516993464052288


In [48]:
from sklearn.tree import DecisionTreeClassifier

# Initialize model with class weight balanced
model = DecisionTreeClassifier(random_state=42, class_weight='balanced')

# Fit the model
model.fit(X_train_scaled, y_train)


DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [50]:
model = DecisionTreeClassifier(random_state=42, class_weight='balanced')
model.fit(X_train_scaled, y_train)


DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [51]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

# Train model with resampled data
model.fit(X_train_res, y_train_res)


DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [52]:
from sklearn.tree import DecisionTreeClassifier

# Create the model with balanced class weights
model = DecisionTreeClassifier(random_state=42, class_weight='balanced')

# Train the model
model.fit(X_train_scaled, y_train)

# Evaluate performance
y_pred = model.predict(X_test_scaled)
from sklearn.metrics import classification_report, confusion_matrix
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.64      0.68        80
           1       0.35      0.41      0.38        41
           2       0.20      0.43      0.27        14
           3       0.24      0.15      0.18        27
           4       0.00      0.00      0.00         8

    accuracy                           0.46       170
   macro avg       0.30      0.33      0.30       170
weighted avg       0.48      0.46      0.46       170

Confusion Matrix:
 [[51 16 10  2  1]
 [13 17  4  6  1]
 [ 2  2  6  4  0]
 [ 4 10  7  4  2]
 [ 0  4  3  1  0]]


In [54]:
from imblearn.over_sampling import SMOTE

# Apply SMOTE to balance the training data
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

# Train the Decision Tree model with the resampled data
model_smote = DecisionTreeClassifier(random_state=42, max_depth=3, min_samples_leaf=2, min_samples_split=2, criterion='entropy')
model_smote.fit(X_train_res, y_train_res)

# Evaluate performance on the test set
y_pred_smote = model_smote.predict(X_test_scaled)
print("SMOTE Classification Report:\n", classification_report(y_test, y_pred_smote))
print("SMOTE Confusion Matrix:\n", confusion_matrix(y_test, y_pred_smote))


SMOTE Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.81      0.79        80
           1       0.36      0.24      0.29        41
           2       0.21      0.21      0.21        14
           3       0.30      0.33      0.32        27
           4       0.07      0.12      0.09         8

    accuracy                           0.52       170
   macro avg       0.34      0.35      0.34       170
weighted avg       0.52      0.52      0.52       170

SMOTE Confusion Matrix:
 [[65  7  1  4  3]
 [14 10  5 12  0]
 [ 1  3  3  4  3]
 [ 2  5  4  9  7]
 [ 2  3  1  1  1]]


In [ ]:
#Model: A Decision Tree Classifier was used for classification.

#Handling Imbalance: SMOTE was applied to balance the classes.

#Performance: The model's accuracy improved, but precision and recall for minority classes were still low.